# Generated by Django 4.2 on 2023-04-19 05:49

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.ProhibitNullCharactersValidator, django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
