# Generated by Django 4.2 on 2023-04-20 04:57

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.ProhibitNullCharactersValidator, django.contrib.auth.validators.ASCIIUsernameValidator()]),
        ),
    ]
