# Generated by Django 4.2 on 2023-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_rename_slot_limit_space_max_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='active',
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('empty', 'empty'), ('pending', 'pending'), ('filled', 'filled')], default='empty'),
        ),
        migrations.AddField(
            model_name='space',
            name='filled_slot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
