# Generated by Django 4.2 on 2023-04-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_remove_slot_active_slot_status_space_filled_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('id', 'space'), name='unique_id_space'),
        ),
    ]
