# Generated by Django 4.2 on 2023-04-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_rename_filled_slot_space_filled_slots_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slot',
            name='unique_id_space',
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('slot_id', 'space'), name='unique_id_space'),
        ),
    ]
