# Generated by Django 4.2 on 2023-04-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_remove_slot_unique_id_space_slot_unique_id_space'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slot',
            name='unique_id_space',
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('slot_id', 'space'), name='unique_slotid_space'),
        ),
    ]
