# Generated by Django 4.2 on 2023-04-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_remove_slot_unique_id_space_slot_unique_slotid_space'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['slot_id']},
        ),
    ]
