# Generated by Django 4.2 on 2023-05-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_alter_slot_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
