# Generated by Django 4.2 on 2023-05-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_alter_space_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('empty', 'empty'), ('pending', 'pending'), ('booked', 'booked')], default='empty'),
        ),
    ]
