# Generated by Django 4.2 on 2023-05-03 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0010_alter_slot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='max_slots',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
